# Increased memory for processing large 26.x decompiled source blocks
org.gradle.jvmargs=-Xmx3G
fabric.loom.disableObfuscation=true

# Target Ecosystem Versions
minecraft_version=26.2
loader_version=0.19.3
fabric_version=0.153.0+26.2
loom_version=1.17-SNAPSHOT

# Mod Configuration
mod_version=1.0-MC26.2
maven_group=com.kobosh
archives_base_name=KoboshAddon